### ISSUE TITLE
多个isAny注解事件只能生效一个

### ISSUE THREAD

**Issue by Fndream** [diyigemt/mirai-boot#10]
这里是return null，会导致有一个没过eventType检查后面的事件就直接就被跳过了。改成continue就行了。我没有权限提交代码。diyigemt有空可以自己改一下更新一下1.0.8。qaq

别问我怎么发现的，都是泪：
被这个神奇的bug整怀疑人生一晚上。我还以为是idea编译的问题，因为有时启动能触发事件，有时启动就不行，然后debug还发现进不去。然后后面发现我断点打到注释上了，就挺尴尬，进去后才发现这里for循环直接return了。就导致比如事件列表里第一个是私聊事件，第二个是群聊事件，然后收到一个群聊消息，进for循环第一个检查是检查私聊没过去，然后直接return掉了，后面的群聊事件直接被抛弃了，emm。难怪有时启动行有时启动不行，群事件要是在第一个就行，要是加载的时候在第二个那就直接被丢了，emm。因为比较急，我自己克隆了一份把这里改成了continue，现在解决了，qaq。diyigemt有空闲时间可以更新一下1.0.8修修bug，qaq
![QQ截图20220421194003](https://user-images.githubusercontent.com/53517522/164453902-cbe35585-4985-4460-a1b3-2324abc967a2.png)

**Comment by diyigemt** [comment]
其实你可以提一个marge请求的qwq
我马上改qwq

**Comment by Fndream** [comment]
> 其实你可以提一个marge请求的qwq 我马上改qwq

对于git我只知道提交和推送，剩下的特性在我的脑瓜里一片空白。加油qwq

**Comment by Fndream** [comment]
> 其实你可以提一个marge请求的qwq 我马上改qwq

别忘了改pom的版本号，我看你的pom提交信息上写着忘了改版本号qwq

**Comment by diyigemt** [comment]
qwq我想顺便升级核心，但是有些接口弃用了qwq再等一下

**Comment by Fndream** [comment]
> qwq我想顺便升级核心，但是有些接口弃用了qwq再等一下

升级核心~好耶~QAQ

**Comment by diyigemt** [comment]
可以了,最新版本1.0.8 qwq 
趁我还或者的这几天提issue吧qwq

**Comment by Fndream** [comment]
233，好的，如果我再遇到问题的话qwq
