### ISSUE TITLE
有没有禁言功能？

### ISSUE THREAD

**Issue by Asuna-forever-god** [diyigemt/mirai-boot#2]
我在您的文档和代码中没有发现与禁言相关的代码，如果想要开发出禁言或更多功能需要去哪里阅读呢?

**Comment by diyigemt** [comment]
可以通过eventPack的getGroup获取当前事件的群然后调用mirai原生的方法
下面是示例
```java
import net.diyigemt.miraiboot.annotation.EventHandler;
import net.diyigemt.miraiboot.annotation.EventHandlerComponent;
import net.diyigemt.miraiboot.entity.MessageEventPack;
import net.diyigemt.miraiboot.entity.PreProcessorData;
import net.diyigemt.miraiboot.permission.CheckPermission;
import net.mamoe.mirai.contact.Group;
import net.mamoe.mirai.contact.NormalMember;

@EventHandlerComponent
public class TestMute {

  @EventHandler(target = "禁言")
  @CheckPermission(isAdminOnly = true)
  public void testMute(MessageEventPack eventPack, PreProcessorData data) {
    Group group = eventPack.getGroup();
    // 根据qq号获取要禁言的对象
    NormalMember normalMember = group.get(12313212L);
    // 禁言1分钟时间
    normalMember.mute(1 * 60);
  }
}

```
可以查看对应的源码注释查看mute的用法: [NormalMember ](https://github.com/mamoe/mirai/blob/2e1ec03daaf6a1e508bc1bc5baeb72796f10c270/mirai-core-api/src/commonMain/kotlin/contact/NormalMember.kt)

**Comment by Asuna-forever-god** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [diyigemt/mirai-boot] 有没有禁言功能？ (#2)





 
可以通过eventPack的getGroup获取当前事件的群然后调用mirai原生的方法
 下面是示例
 import net.diyigemt.miraiboot.annotation.EventHandler; import net.diyigemt.miraiboot.annotation.EventHandlerComponent; import net.diyigemt.miraiboot.entity.MessageEventPack; import net.diyigemt.miraiboot.entity.PreProcessorData; import net.diyigemt.miraiboot.permission.CheckPermission; import net.mamoe.mirai.contact.Group; import net.mamoe.mirai.contact.NormalMember; @EventHandlerComponent public class TestMute {   @EventHandler(target = "禁言")   @CheckPermission(isAdminOnly = true)   public void testMute(MessageEventPack eventPack, PreProcessorData data) {     Group group = eventPack.getGroup();     // 根据qq号获取要禁言的对象     NormalMember normalMember = group.get(12313212L);     // 禁言1分钟时间     normalMember.mute(1 * 60);   } } 
 
可以查看对应的源码注释查看mute的用法: NormalMember

**Comment by Asuna-forever-god** [comment]
最近启动时发现&nbsp;SendMessageLib类的图片发送函数并不能发送图片到qq群
只能用此函数发送图片到好友,不知道友可有解决方法望告知。

**Comment by diyigemt** [comment]
SendMessageLib类发送消息是直接向产生event的事件发送的，理论上如果传入的是群事件，发送的方向也是向群里发送
有可能是被夹了，这种情况下log里还是会显示发送了图片，但是群里却没有

**Comment by diyigemt** [comment]
有可能是与核心的[这个issue#1536](https://github.com/mamoe/mirai/issues/1536)有关
影响的版本是低于2.7.1的，目前使用的版本是2.6.3
最近会更新一次核心版本，会在这时修复

**Comment by diyigemt** [comment]
已更新
