### ISSUE TITLE
@EventHandler注解target为空时无法处理任何事件

### ISSUE THREAD

**Issue by Fndream** [diyigemt/mirai-boot#9]
你好~ 我阅读了文档中
> target：
miriaboot是基于指令响应的机器人，期望所有事件处理器都需要有一个对应的指令才会触发，指令仅支持纯中文|英文数字混合两种类型。***当target留空时，所有消息事件均会触发这个消息事件处理器。***

我试图创建一个群消息监听事件以使用反射特性方便我进行复杂指令的管理。但如图1，经过测试发现当target为其默认值"空字符串"时，该方法并不会被触发，包括下面的私聊事件。不知是否为bug。为了排除不是我的使用方式有问题，图2正常使用EventHandler注解可以进行正常工作。

……以普遍理性而论，我认为 `@EventHandler(type = EventHandlerType.MESSAGE_HANDLER_GROUP)` 这种使用方式可以监听群消息事件不检测指令条件是科学合理的 qaq。还是说真的是 "**所有事件处理器都需要有一个对应的指令才会触发**" 原则 qwq。但是 "**当target留空时，所有消息事件均会触发这个消息事件处理器。**" qwq

图3 (依赖版本)：miraiboot : 1.0.7  mirai-core : 2.10.1

![QQ截图20220418204102](https://user-images.githubusercontent.com/53517522/163809871-966aef9d-feb6-4c85-88a6-74ad0a8472af.png)
![QQ截图20220418204116](https://user-images.githubusercontent.com/53517522/163809875-85d9e786-c7f3-43da-8018-056ae9429312.png)
![QQ截图20220418210633](https://user-images.githubusercontent.com/53517522/163812652-e7cb04f2-d425-4bef-ba0c-709d52738b00.png)

**Comment by Fndream** [comment]
经过我1小时对miraiboot的debug，对不起，原来isAny是可以和type一起用的，那为什么！为什么文档里说isAny会忽略 "**target，split，start，type**" 的设置！应该把文档中的type删掉 qwq，问题已解决 
现在这样使用→ `@EventHandler(type = EventHandlerType.MESSAGE_HANDLER_GROUP, isAny = true)`  可以做到检测群消息事件了不考虑指令了，好耶~

我以为isAny是所有消息类型都处理，再加上文档说会忽略掉type，就没考虑isAny。然后我抱着isAny要是直接所有事件混合处理的话那岂不是很鸡肋的心态去试了试isAny，然后debug发现isAny是会进行checkEventType方法检查的 qwq。所以，屑diyigemt去改下文档啦！qwq a！ (╯▔皿▔)╯ 

> isAny：
当其值为true时，注册一个强制触发的消息事件处理器，忽略target，split，start，type的参数设置，处理所有类型的消息事件。

![QQ截图20220418223302](https://user-images.githubusercontent.com/53517522/163823715-91657ea7-760b-40cb-b6a8-27b024473aec.png)
![QQ截图20220418223414](https://user-images.githubusercontent.com/53517522/163823733-71486d6f-ce4b-4b88-9add-22ab23f37862.png)
![QQ截图20220418223443](https://user-images.githubusercontent.com/53517522/163823741-1a229fc5-c74f-4df8-a89e-66ed2ac519fa.png)

**Comment by diyigemt** [comment]
抱歉因为文档的错误给你照成了困扰qwq，我马上改
不过可以的话建议使用其他更好的框架
现在的mirai社区已经有更多更好的集成了mirai的java开发框架了
就如开发文档开头说的，这个项目是我在mirai初期苦于没有一个好用的java开发框架而建立的
而现在因为事情太多了目前这个项目已经失去了及时维护的可能(通过最后的开发分支也能看出来qwq)(你看我现在才回你)
我只能说尽量维护吧

**Comment by Fndream** [comment]
> 抱歉因为文档的错误给你照成了困扰qwq，我马上改 不过可以的话建议使用其他更好的框架 现在的mirai社区已经有更多更好的集成了mirai的java开发框架了 就如开发文档开头说的，这个项目是我在mirai初期苦于没有一个好用的java开发框架而建立的 而现在因为事情太多了目前这个项目已经失去了及时维护的可能(通过最后的开发分支也能看出来qwq)(你看我现在才回你) 我只能说尽量维护吧

哈哈！没事的，谁也不可能有这么多私有时间去维护项目qwq，当时在论坛看到这个项目的时候，就感觉非常的棒！主要是文档写的太详细啦！非常适合我喜欢写点文游玩具的类型！尤其是MessageEventPack！qwq，有时间有精力的时候再回来更新。自己主要的事情要紧，嘿嘿QAQ~
